### ISSUE TITLE
Cannot build with Node v10.0.0

### ISSUE THREAD

**Issue by BlinkyStitt** [kvhnuke/etherwallet#1804]
Looks like the sha3 package is broken on node 10:
```
$ npm install
...
npm ERR! sha3@1.2.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the sha3@1.2.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

What version of node is this site targeting? I rolled back to node 9 with the help of nvm and it installs everything fine.

This should probably also be opened as an issue on the sha3 package.

**Comment by geahaad** [comment]
Same here. Build on OSX w/ Node v10.1.0 fails.
```
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:235:12)
gyp ERR! System Darwin 17.6.0
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/geahaad/dev/etherwallet/node_modules/sha3
gyp ERR! node -v v10.1.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```
Rolling back to v9.4.0 helped.
