### ISSUE TITLE
Cannot send transaction

### ISSUE THREAD

**Issue by batousik** [kvhnuke/etherwallet#2132]
etherwallet-master.js:57263 Uncaught (in promise) DOMException: Failed to execute 'send' on 'RTCDataChannel': RTCDataChannel.readyState is not 'open'
    at Peer.send (https://www.myetherwallet.com/js/etherwallet-master.js:57263:17)
    at MewConnectInitiator._callee8$ (https://www.myetherwallet.com/js/etherwallet-master.js:33656:24)
    at tryCatch (https://www.myetherwallet.com/js/etherwallet-master.js:111704:40)
    at Generator.invoke [as _invoke] (https://www.myetherwallet.com/js/etherwallet-master.js:111942:22)
    at Generator.prototype.(anonymous function) [as next] (https://www.myetherwallet.com/js/etherwallet-master.js:111756:21)
    at step (https://www.myetherwallet.com/js/etherwallet-master.js:32582:30)
    at https://www.myetherwallet.com/js/etherwallet-master.js:32593:13
Peer.send @ etherwallet-master.js:57263
_callee8$ @ etherwallet-master.js:33656
tryCatch @ etherwallet-master.js:111704
invoke @ etherwallet-master.js:111942
prototype.(anonymous function) @ etherwallet-master.js:111756
step @ etherwallet-master.js:32582
(anonymous) @ etherwallet-master.js:32593
Promise.then (async)
step @ etherwallet-master.js:32592
(anonymous) @ etherwallet-master.js:32600
(anonymous) @ etherwallet-master.js:32579
rtcSend @ etherwallet-master.js:33674
sendRtcMessage @ etherwallet-master.js:33596
signTransaction @ etherwallet-master.js:19988
uiFuncs.signTxMewConnect @ etherwallet-master.js:32122
genTxWithInfo @ etherwallet-master.js:32188
(anonymous) @ etherwallet-master.js:32214
(anonymous) @ etherwallet-master.js:16737
callback @ etherwallet-master.js:16790
(anonymous) @ etherwallet-master.js:16779
processQueue @ etherwallet-master.js:90469
(anonymous) @ etherwallet-master.js:90517
$digest @ etherwallet-master.js:91630
$apply @ etherwallet-master.js:92018
done @ etherwallet-master.js:85867
completeRequest @ etherwallet-master.js:86124
requestLoaded @ etherwallet-master.js:86029
load (async)
(anonymous) @ etherwallet-master.js:86012
sendReq @ etherwallet-master.js:85812
serverRequest @ etherwallet-master.js:85553
processQueue @ etherwallet-master.js:90469
(anonymous) @ etherwallet-master.js:90517
$digest @ etherwallet-master.js:91630
$apply @ etherwallet-master.js:92018
done @ etherwallet-master.js:85867
completeRequest @ etherwallet-master.js:86124
requestLoaded @ etherwallet-master.js:86029
load (async)
(anonymous) @ etherwallet-master.js:86012
sendReq @ etherwallet-master.js:85812
serverRequest @ etherwallet-master.js:85553
processQueue @ etherwallet-master.js:90469
(anonymous) @ etherwallet-master.js:90517
$digest @ etherwallet-master.js:91630
$apply @ etherwallet-master.js:92018
done @ etherwallet-master.js:85867
completeRequest @ etherwallet-master.js:86124
requestLoaded @ etherwallet-master.js:86029
load (async)
(anonymous) @ etherwallet-master.js:86012
sendReq @ etherwallet-master.js:85812
serverRequest @ etherwallet-master.js:85553
processQueue @ etherwallet-master.js:90469
(anonymous) @ etherwallet-master.js:90517
$digest @ etherwallet-master.js:91630
$apply @ etherwallet-master.js:92018
(anonymous) @ etherwallet-master.js:101374
defaultHandlerWrapper @ etherwallet-master.js:76360
eventHandler @ etherwallet-master.js:76348

**Comment by gamalielhere** [comment]
@batousik is this still an issue?

**Comment by gamalielhere** [comment]
Closing for inactivity.
