### ISSUE TITLE
AssertionError thrown from mew-custom@1.1.0

### ISSUE THREAD

**Issue by aekasitt** [kvhnuke/etherwallet#2164]
Environment Review
---

I just cloned the project to my MacBook Pro running macOS High Sierra 10.13.6
I reset HEAD back to the latest Release at Commit `c4dc1d7e Release: v3.26.0`
My node version is as seen below.
> npm --version  
> 6.4.1  

Issue Faced
---
Cannot start running dev server on my local machine. I see some warnings thrown when installing modules as seen below:
> npm install  
```
...
npm WARN mew-custom@1.1.0 No repository field.
npm WARN The package babel-preset-env is included as both a dev and production dependency.

added 2824 packages from 1913 contributors and audited 12979 packages in 104.797s
found 8 vulnerabilities (2 low, 6 high)
```

-----
And when I try to start running on dev, I get the following error.

> npm run dev  
```
> mew-custom@1.1.0 dev ~/workspaces/etherwallet
> gulp

assert.js:351
    throw err;
    ^

AssertionError [ERR_ASSERTION]: Task function must be specified
    at Gulp.set [as _setTask] (~/workspaces/etherwallet/node_modules/undertaker/lib/set-task.js:10:3)
    at Gulp.task (~/workspaces/etherwallet/node_modules/undertaker/lib/task.js:13:8)
    at Object.<anonymous> (~/workspaces/etherwallet/gulpfile.js:179:6)
    at Module._compile (internal/modules/cjs/loader.js:707:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:718:10)
    at Module.load (internal/modules/cjs/loader.js:605:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:544:12)
    at Function.Module._load (internal/modules/cjs/loader.js:536:3)
    at Module.require (internal/modules/cjs/loader.js:643:17)
    at require (internal/modules/cjs/helpers.js:22:18)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! mew-custom@1.1.0 dev: `gulp`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the mew-custom@1.1.0 dev script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

**Comment by gamalielhere** [comment]
@aekazitt what node version are you using?

**Comment by aekasitt** [comment]
Node:
> node -v  
> v11.1.0  

-----
Npm:
> npm -v  
> 6.4.1

**Comment by kvhnuke** [comment]
Try node 8
