### ISSUE TITLE
Tokens: Don't die if a person adds a bad custom token + Add way for user to easliy remove custom token

### ISSUE THREAD

**Issue by tayvano** [kvhnuke/etherwallet#231]
### Part 1

✅  If you add a token that is not actually a token (or perhaps not ERC-20 compliant) the token page and all subsequently loaded pages in that session will fail. 

**Error in console:**

```
etherwallet-master.js:29259 BigNumber Error: new BigNumber() not a number: 0x
    at raise (https://www.myetherwallet.com/js/etherwallet-master.js:49417:23)
    at https://www.myetherwallet.com/js/etherwallet-master.js:49406:27
    at new BigNumber (https://www.myetherwallet.com/js/etherwallet-master.js:48419:57)
    at https://www.myetherwallet.com/js/etherwallet-master.js:2712:31
    at https://www.myetherwallet.com/js/etherwallet-master.js:72:9
    at processQueue (https://www.myetherwallet.com/js/etherwallet-master.js:31643:34)
    at https://www.myetherwallet.com/js/etherwallet-master.js:31660:13
    at Scope.$eval (https://www.myetherwallet.com/js/etherwallet-master.js:32883:34)
    at Scope.$digest (https://www.myetherwallet.com/js/etherwallet-master.js:32705:37)
    at Scope.$apply (https://www.myetherwallet.com/js/etherwallet-master.js:32991:30)(anonymous function) @ etherwallet-master.js:29259(anonymous function) @ etherwallet-master.js:25986processQueue @ etherwallet-master.js:31651(anonymous function) @ etherwallet-master.js:31660$eval @ etherwallet-master.js:32883$digest @ etherwallet-master.js:32705$apply @ etherwallet-master.js:32991done @ etherwallet-master.js:27303completeRequest @ etherwallet-master.js:27501requestLoaded @ etherwallet-master.js:27439
```

**To recreate**

Add a custom token using '0x7cB57B5A97eAbe94205C07890BE4c1aD31E486A8' + "Bad Token" + "1" Decimal.

*\* Fix**

Display error message next to bad token. Check to see if its valid before adding it?

---
### Part 2

✅ Click on the X that I just added next to custom tokens should remove that token from local storage.

---
### Part 3

Add "loading..." to ETH/ETC/EUR/USD/BTC like we did with tokens.

---
### Part 4

display globalFuncs.errorMsgs[20] in validateTokenBalances instead of as an alert

---
### Part 5 (taylor)

Check other pages, translations, CX

**Comment by tayvano** [comment]
Done and doner
