### ISSUE TITLE
Ratelimiting

### ISSUE THREAD

**Issue by 0xcaff** [kvhnuke/etherwallet#906]
Due to the recent mainnet.infura.io outages, I decided to switch some code I was using to from infura to the myetherwallet JSON RPC interface. During this time, the following error occasionally occurred.

    Error: Invalid JSON RPC response: "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.01 Transitional//EN\" \"http://www.w3.org/TR/html4/loose.dtd\">\n<HTML><HEAD><META HTTP-EQUIV=\"Content-Type\" CONTENT=\"text/html; charset=iso-8859-1\">\n<TITLE>ERROR: The request could not be satisfied</TITLE>\n</HEAD><BODY>\n<H1>ERROR</H1>\n<H2>The request could not be satisfied.</H2>\n<HR noshade size=\"1px\">\nThe origin closed the connection.\n<BR clear=\"all\">\n<HR noshade size=\"1px\">\n<PRE>\nGenerated by cloudfront (CloudFront)\nRequest ID: GQeM8ZIaLpwEBaAjAgi5g3i2D2cnKfkdvJn6vBguj-UmSoT7GSxG-g==\n</PRE>\n<ADDRESS>\n</ADDRESS>\n</BODY></HTML>"
        at Object.InvalidResponse (/home/drone/projects/mew/asset-position-disposal/node_modules/web3/lib/web3/errors.js:38:16)
        at XMLHttpRequest.request.onreadystatechange (/home/drone/projects/mew/asset-position-disposal/node_modules/web3/lib/web3/httpprovider.js:115:32)
        at XMLHttpRequestEventTarget.dispatchEvent (/home/drone/projects/mew/asset-position-disposal/node_modules/xhr2/lib/xhr2.js:64:18)
        at XMLHttpRequest._setReadyState (/home/drone/projects/mew/asset-position-disposal/node_modules/xhr2/lib/xhr2.js:354:12)
        at XMLHttpRequest._onHttpResponseEnd (/home/drone/projects/mew/asset-position-disposal/node_modules/xhr2/lib/xhr2.js:509:12)
        at IncomingMessage.<anonymous> (/home/drone/projects/mew/asset-position-disposal/node_modules/xhr2/lib/xhr2.js:469:24)
        at emitNone (events.js:110:20)    
        at IncomingMessage.emit (events.js:207:7)                                
        at endReadableNT (_stream_readable.js:1047:12)                           
        at _combinedTickCallback (internal/process/next_tick.js:102:11)

What is this? Does myetherwallet implement ratelimiting? MEW is an awesome thing. Thanks for making it. 😄

**Comment by tayvano** [comment]
Yes you cannot do more than 400 requests per minute thru our API. This should be more than sufficient. If you want more, I recommend getting your own node. You can find our node setup in the MyEtherWallet GitHub org under geth-docker-lb or something (on mobile)

**Comment by 0xcaff** [comment]
Thanks!
